### ISSUE TITLE
Bug: Crafting not possible in Handy Bag UI

### ISSUE THREAD

**Issue by SargeRyong** [maruohon/enderutilities#68]
Just experienced this issue in SevTech 3.0.7 with EnderUtils 0.7.8.

When using either size of handy bag, the 4-slot inventory crafting grid does not function.  Placing items in there does not result in crafting outputs.  Normal crafting tables are still able to create these  2x2 recipes.  Disabling the bag (and thereby switching to the default inventory GUI) enables the player to craft normally, but while the bag is active, crafting cannot be done.

Issue occurs whether or not any modules are installed, and regardless of whether any of the bags have items in them.  Doesn't seem related to any of the bag options being enabled or disabled.  No stack trace or other errors in log.

**Comment by SargeRyong** [comment]
As an addendum, it seems not all crafting doesnt work  - only most of it.  For example, I can craft cobble into rocks, but I cant craft redstone blocks into dust, or create levers or crafting tables.

**Comment by maruohon** [comment]
Hmm, well it seems to work just fine on it's own in my test instance, so it must be some kind of cross-mod issue in the pack. From what I understand, the pack has Game Stages/Recipe Stages and whatnot, are you sure those are not locking out the recipes? Although you said they do work in the regular player inventory crafting grid... hmm. Do the Creation Station crafting grids have similar issues as well?

**Comment by SargeRyong** [comment]
Positive that the recipe's I'm trying to make are staged.  (as you noted, they work in other crafting grids - have tried inventory, vanilla, and tinker's crafting station, and they all work).  

Just checked the Creation Station and it does have the same issue as the Handy Bag.

I think you may be onto something with it being related to recipe stages.  All of the items that I can successfully create are ones that available to the player at the very beginning of the game (rocks, flint hatchets, plant twine, grass fiber mesh - all items that do not require staging).  

I'm willing to bet they aren't playing nice with recipe stages in some way.

**Comment by maruohon** [comment]
I'll have to ask around how exactly those staging mods work and what I might be doing wrong with my crafting stuff. I'll also have to look at my code for that as I don't remember anymore how that stuff works exactly.

**Comment by maruohon** [comment]
Could you please test if this build fixes the issue? Thanks.

https://masa.dy.fi/tmp/minecraft/mods/enderutilities/enderutilities-1.12.2-0.7.9-dev.20180524.132352.jar

**Comment by SargeRyong** [comment]
Crashes during initialization:

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;)V
	at fi.dy.masa.enderutilities.registry.EnderUtilitiesBlocks.registerTileEntity(EnderUtilitiesBlocks.java:164)
	at fi.dy.masa.enderutilities.registry.EnderUtilitiesBlocks.registerTileEntities(EnderUtilitiesBlocks.java:141)
	at fi.dy.masa.enderutilities.registry.EnderUtilitiesBlocks.registerBlocks(EnderUtilitiesBlocks.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_316_EnderUtilitiesBlocks_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3390)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by maruohon** [comment]
Oh, I just updated to the latest Forge build (2702) yesterday in my dev environment... It seems this build would need at least Forge 2694 due to one registration method change. Not sure if it's possible to update Forge in your pack without breaking everything? I could at least do a new dev build with that Forge change reverted to test with, if you want?

**Comment by SargeRyong** [comment]
If it's no trouble, that would be nice, just to test it in isolation in the exact circumstances where it occurred.

**Comment by maruohon** [comment]
Okay, this build has that registration change reversed: https://masa.dy.fi/tmp/minecraft/mods/enderutilities/enderutilities-1.12.2-0.7.9-dev.20180524.141654.jar

**Comment by SargeRyong** [comment]
Yep!  Confirmed, the fix works in both of the crafting UIs.
